### PR TITLE
A few mini fixes

### PR DESCRIPTION
**Pull request by kenchris**
- Remove unneeded code for fetching the JSON, like manually asking for a re-render
- Avoid using SVG in the lazy image element. Instead use visibility:hidden (element is then in DOM, unlike with display: none and IntersectionObserver will find it)

### CODE REVIEW

**Comment by rakuco** [comment]
Well, could you mention here and in the commit message what those fixes are... fixing? :-)

**Comment by rakuco** [comment]
Thanks, can you add those details to the pull request message too?

**Comment by kenchris** [comment]
done

**Comment by rakuco** [comment]
aaaand merging

**Pull request merged**
