### PR TITLE
Add support for GravitySensor

### PR DESCRIPTION
**Pull request by reillyeon**

### CODE REVIEW

**Comment by reillyeon** [comment]
@rakuco, please take a look.

**Comment by reillyeon** [comment]
Oops, @rakuco is on vacation. @kenchris, can you merge this quickly?

**Comment by reillyeon** [comment]
It looks like there isn't an automated process to rebuild and publish to GitHub Pages. Can you take care of that?

**Comment by kenchris** [comment]
Oh. Let me write someone as I am on vacation and without my laptop

**Comment by rakuco** [comment]
I've filed #96 to track publishing new commits automatically, we just need a volunteer to take care of it :-)

**Pull request merged**
